name: 'Main'

on:
  push:
    branches: ['master', 'main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-frontend/setup@v1.0
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Publish Angular Thrift
        uses: valitydev/action-frontend/publish@v1.0
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          directory: ./projects/ng-thrift/dist
      - name: Publish on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ng-thrift-doc/browser
