name: 'PR'

on:
  pull_request:
    branches: ['*']
#  pull_request_target:
#    types: ['labeled']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: $(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-frontend/setup@v1.0
      - run: npm ci
      - name: Check
        run: npm run check
      - name: Test
        run: npm run test:ci
      - name: Build
        run: npm run build
      - name: Publish Angular Thrift
        if: contains(github.event.pull_request.labels.*.name, 'publish') || contains(github.event.pull_request.labels.*.name, 'publish ng-thrift')
        working-directory: ./projects/ng-thrift/dist
        run: npm version prerelease --preid pr-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag pr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
